name: Redis Service Example

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  runner-job:
    runs-on: ubuntu-latest

    # container:
    #   image:  python:3.7

    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v1
      # - name: Set up Python
      #   uses: cclauss/GitHub-Action-for-pytest@0.5.0
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.11
      - name: Test with pytest
        env:
          REDISTOGO_URL: ${{ secrets.REDISTOGO_URL }}
        run: |
          ( pip install redis==3.5.3 && 
            pip install pytest && 
            echo REDISTOGO_URL="$REDISTOGO_URL" &&
            pytest test.py )