name: Redis Service Example

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image:  node:10.16-jessie

    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' 
      - name: Code Style Checks - Python
        run: |
          pip install --upgrade pip
          pip install pytest

      - name: Redis - Basic Test
        run: pytest test.py
      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
           -${{ hashFiles('virtual_env_reqs/extra-reqs-ci.txt') }}