name: Redis Service Example

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image:  python:3.8

    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
      - name: Test with pytest
        run: |
          pytest test.py 